### ISSUE TITLE
Post-it contents not preserving through toggles

### ISSUE THREAD

**Issue by Voidraizer** [blish-hud/bhud-pkgs#162]
[BlishPad Issue I posted accidentally here] I'm not sure if it's intended to, but the Preserve Post-It Contents option does not preserve the contents between toggles.  Noting something down and toggling it away to clear screen real estate seems like normal operating procedure but upon toggling the post-it back, the contents are reset

**Comment by dlamkins** [comment]
@Snaid1 This issue was opened on the wrong repo here.  Wanted to tag you here for reference just so that you could see it.

**Comment by Voidraizer** [comment]
Oh I'm sorry, I'm still really bad with GitHub.

**Comment by dlamkins** [comment]
> Oh I'm sorry, I'm still really bad with GitHub.

Hey, no worries mate.  Just wanted to make sure that the right people saw the issue to ensure we got a response for you.  🙂

**Comment by Snaid1** [comment]
Thanks for tagging me. I opened an issue on the Blishpad Repo for this. feel free to close/hide this issue in the bhud-pkgs repo if you want.  
@Voidraizer you can track this issue here going forward: https://github.com/Snaid1/BHUD-Blishpad/issues/46
